name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  
     
      - name: informations
        run: |
          echo " Evento: ${{ github.event_name }}"
          echo " Branch: ${{ github.ref_name }}"
          echo " Who did: ${{ github.actor }}"
          echo " Repository: ${{ github.repository }}"
        
